# EDA - Solar and Lunar Eclipses data
Short EDA on dataset to get an understanding of the data

In [1]:
import pandas as pd 

# Read data 
df = pd.read_csv("lunar.csv")
df.head(10)

,Catalog Number,Calendar Date,Eclipse Time,Delta T (s),Lunation Number,Saros Number,Eclipse Type,Quincena Solar Eclipse,Gamma,Penumbral Magnitude,Umbral Magnitude,Latitude,Longitude,Penumbral Eclipse Duration (m),Partial Eclipse Duration (m),Total Eclipse Duration (m)
0,1,-1999 June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-
1,2,-1999 November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-
2,3,-1998 May 17,05:47:36,46416,-49445,-11,P,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,-
3,4,-1998 November 11,05:15:58,46404,-49439,-6,P,-a,-0.4644,2.0382,0.9740,12N,113E,343.4,200.8,-
4,5,-1997 May 6,18:57:01,46392,-49433,-1,T+,pp,0.1003,2.6513,1.6963,11S,92W,322.8,213.5,98.2
5,6,-1997 October 31,06:54:09,46380,-49427,4,T+,pp,0.2207,2.5057,1.4014,9N,88E,374.4,228.7,90.6
6,7,-1996 April 25,11:57:19,46368,-49421,9,P,a-,-0.6385,1.6562,0.7159,7S,13E,288.6,166,-
7,8,-1996 October 19,06:00:26,46357,-49415,14,P,t-,0.8915,1.2694,0.1756,5N,101E,308.8,100.1,-
8,9,-1995 March 16,18:59:06,46347,-49410,-19,N,-a,1.2015,0.6538,-0.3471,10N,87W,217.0,-,-
9,10,-1995 April 15,04:12:15,46345,-49409,19,N,a-,-1.4029,0.2681,-0.7010,4S,130E,139.5,-,-

In [2]:
# See what columns there are
df.columns

Index(['Catalog Number', 'Calendar Date', 'Eclipse Time', 'Delta T (s)',
       'Lunation Number', 'Saros Number', 'Eclipse Type',
       'Quincena Solar Eclipse', 'Gamma', 'Penumbral Magnitude',
       'Umbral Magnitude', 'Latitude', 'Longitude',
       'Penumbral Eclipse Duration (m)', 'Partial Eclipse Duration (m)',
       'Total Eclipse Duration (m)'],
      dtype='str')

In [3]:
# See how many rows and columns there are
rows, cols = df.shape
print(f"rows: {rows}, columns: {cols}")

rows: 12064, columns: 16

In [4]:
# See information about columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12064 entries, 0 to 12063
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Catalog Number                  12064 non-null  int64
 1   Calendar Date                   12064 non-null  str
 2   Eclipse Time                    12064 non-null  str
 3   Delta T (s)                     12064 non-null  int64
 4   Lunation Number                 12064 non-null  int64
 5   Saros Number                    12064 non-null  int64
 6   Eclipse Type                    12064 non-null  str
 7   Quincena Solar Eclipse          12064 non-null  str
 8   Gamma                           12064 non-null  float64
 9   Penumbral Magnitude             12064 non-null  float64
 10  Umbral Magnitude                12064 non-null  float64
 11  Latitude                        12064 non-null  str
 12  Longitude                       12064 non-null  str
 13  Penumbral Eclipse Duration (m)  12064 non-null  float64
 14  Partial Eclipse Duration (m)    12064 non-null  str
 15  Total Eclipse Duration (m)      12064 non-null  str
dtypes: float64(4), int64(4), str(8)
memory usage: 1.5 MB

In [5]:
df.describe()

,Catalog Number,Delta T (s),Lunation Number,Saros Number,Gamma,Penumbral Magnitude,Umbral Magnitude,Penumbral Eclipse Duration (m)
count,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000
mean,6032.500000,12116.476044,-18531.392822,80.505056,0.002490,1.418656,0.400175,269.971941
std,3482.721158,13584.785584,17887.218741,48.416007,0.910505,0.832263,0.832954,79.945444
min,1.000000,-6.000000,-49456.000000,-20.000000,-1.582700,0.000400,-1.095800,5.200000
25%,3016.750000,962.000000,-33923.250000,40.000000,-0.788825,0.684425,-0.334000,223.100000
50%,6032.500000,5597.000000,-18445.500000,80.000000,0.001750,1.417450,0.400450,295.000000
75%,9048.250000,20901.500000,-3067.750000,121.000000,0.791725,2.136900,1.117925,327.800000
max,12064.000000,46437.000000,12378.000000,183.000000,1.579100,2.908900,1.882100,379.500000

In [6]:
df["Saros Number"].value_counts()

Saros Number
 47     86
 65     86
 27     85
 26     85
 43     85
        ..
-18      6
-19      5
-20      3
 182     3
 183     2
Name: count, Length: 204, dtype: int64

In [7]:
df["Eclipse Type"].value_counts()

Eclipse Type
P     4207
N     4020
T     1405
T+    1042
T-    1032
Nx     141
Ne     115
Nb     102
Name: count, dtype: int64

In [8]:
df.columns = df.columns.str.replace(' ','_')
df

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m)
0,1,-1999 June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-
1,2,-1999 November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-
2,3,-1998 May 17,05:47:36,46416,-49445,-11,P,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,-
3,4,-1998 November 11,05:15:58,46404,-49439,-6,P,-a,-0.4644,2.0382,0.9740,12N,113E,343.4,200.8,-
4,5,-1997 May 6,18:57:01,46392,-49433,-1,T+,pp,0.1003,2.6513,1.6963,11S,92W,322.8,213.5,98.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12059,12060,2999 May 21,13:21:13,4417,12360,166,P,t-,0.4971,1.9853,0.9069,20S,178E,356.7,204.2,-
12060,12061,2999 November 14,16:41:25,4421,12366,171,T,a-,-0.4669,1.9868,1.0153,18N,124E,308.0,189.1,18.5
12061,12062,3000 May 10,15:00:16,4424,12372,176,N,t-,1.2117,0.6604,-0.3907,17S,153E,230.6,-,-
12062,12063,3000 October 5,17:10:38,4427,12377,143,Ne,-h,1.5497,0.0329,-1.0039,6N,118E,53.5,-,-
12063,12064,3000 November 4,05:45:18,4428,12378,181,N,h-,-1.2170,0.6326,-0.3828,14N,72W,214.8,-,-

In [9]:
import duckdb

duckdb.sql("""--sql
SELECT Calendar_Date, SUBSTRING(Calendar_Date, 1, 5) AS test
FROM df

LIMIT 5;
""").df()

       Calendar_Date   test
0      -1999 June 26  -1999
1  -1999 November 21  -1999
2       -1998 May 17  -1998
3  -1998 November 11  -1998
4        -1997 May 6  -1997

In [10]:


df["Year"] = df["Calendar_Date"].str.extract(r"^(-?\d{1,4})", expand=False)
df["Calendar_Date"] = df["Calendar_Date"].str.replace(r"^(-?\d{1,4})", "", regex=True)
df.head(3)

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m),Year
0,1,June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-,-1999
1,2,November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-,-1999
2,3,May 17,05:47:36,46416,-49445,-11,P,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,-,-1998

In [11]:
df["Year"].value_counts()

Year
-1926    5
-1796    5
-1731    5
-1275    5
-1210    5
        ..
2994     2
2995     2
2996     2
2998     2
2999     2
Name: count, Length: 5000, dtype: int64